import type { DatabaseSync } from 'node:sqlite';
import type { CommandLevel } from '../command-registry.js';

export interface OAuthGrant {
  userId:string; clientId:string; clientName:string; visibleLevels:CommandLevel[];
  level5PermanentlyHidden:boolean; createdAt:number; updatedAt:number; revokedAt?:number; lastUsedAt?:number;
}
function levels(value:string):CommandLevel[]{return value.split(',').filter(Boolean).map(Number).filter((v):v is CommandLevel=>v>=1&&v<=5) as CommandLevel[];}
export class SqliteOAuthGrantStore {
  constructor(private readonly db:DatabaseSync){}
  get(userId:string,clientId:string):OAuthGrant|undefined{const r=this.db.prepare('SELECT * FROM oauth_grants WHERE user_id=? AND client_id=?').get(userId,clientId) as any;return r?{userId:r.user_id,clientId:r.client_id,clientName:r.client_name,visibleLevels:levels(r.visible_levels ?? r.allowed_levels ?? ''),level5PermanentlyHidden:!!(r.level5_permanently_hidden ?? r.level5_permanently_denied),createdAt:r.created_at,updatedAt:r.updated_at,...(r.revoked_at?{revokedAt:r.revoked_at}:{}),...(r.last_used_at?{lastUsedAt:r.last_used_at}:{})}:undefined;}
  upsert(userId:string,clientId:string,clientName:string,visibleLevels:CommandLevel[],level5PermanentlyHidden:boolean):void{const now=Date.now(),normalized=[...new Set(visibleLevels)].sort((a,b)=>a-b).join(',');this.db.prepare('INSERT INTO oauth_grants (user_id,client_id,client_name,visible_levels,level5_permanently_hidden,created_at,updated_at,revoked_at,last_used_at) VALUES (?,?,?,?,?,?,?,NULL,NULL) ON CONFLICT(user_id,client_id) DO UPDATE SET client_name=excluded.client_name,visible_levels=excluded.visible_levels,level5_permanently_hidden=excluded.level5_permanently_hidden,updated_at=excluded.updated_at,revoked_at=NULL').run(userId,clientId,clientName,normalized,level5PermanentlyHidden?1:0,now,now);}
  revoke(userId:string,clientId:string):void{const now=Date.now();this.db.prepare('UPDATE oauth_grants SET revoked_at=?,updated_at=? WHERE user_id=? AND client_id=?').run(now,now,userId,clientId);}
  update(userId:string,clientId:string,visibleLevels:CommandLevel[],level5PermanentlyHidden:boolean):void{const current=this.get(userId,clientId);if(!current)throw new Error('OAuth source not found.');if(current.level5PermanentlyHidden&&!level5PermanentlyHidden)throw new Error('Level 5 has been permanently hidden for this OAuth source.');if((current.level5PermanentlyHidden||level5PermanentlyHidden)&&visibleLevels.includes(5))throw new Error('Level 5 cannot be shown when it is permanently hidden.');const now=Date.now(),normalized=[...new Set(visibleLevels)].sort((a,b)=>a-b).join(',');this.db.prepare('UPDATE oauth_grants SET visible_levels=?,level5_permanently_hidden=?,updated_at=?,revoked_at=NULL WHERE user_id=? AND client_id=?').run(normalized,level5PermanentlyHidden?1:0,now,userId,clientId);}
  touch(userId:string,clientId:string):void{this.db.prepare('UPDATE oauth_grants SET last_used_at=? WHERE user_id=? AND client_id=? AND revoked_at IS NULL').run(Date.now(),userId,clientId);}
  list(userId:string):OAuthGrant[]{const rows=this.db.prepare('SELECT * FROM oauth_grants WHERE user_id=? ORDER BY client_name,client_id').all(userId) as any[];return rows.map(r=>({userId:r.user_id,clientId:r.client_id,clientName:r.client_name,visibleLevels:levels(r.visible_levels ?? r.allowed_levels ?? ''),level5PermanentlyHidden:!!(r.level5_permanently_hidden ?? r.level5_permanently_denied),createdAt:r.created_at,updatedAt:r.updated_at,...(r.revoked_at?{revokedAt:r.revoked_at}:{}),...(r.last_used_at?{lastUsedAt:r.last_used_at}:{})}));}
  isVisible(userId:string,clientId:string,level:CommandLevel):boolean{const g=this.get(userId,clientId);return !!g&&!g.revokedAt&&g.visibleLevels.includes(level);}
}
